version: "3"
services:
  semantic_server:
    image: knowledgelinks/semantic-server
      deploy:
        replicas: 3
        resources:
          limits:
            cpus: "0.2"
            memory: 2G
        restart_policy:
          condition: on-failure
      ports:
        - "8080:8080"
        - "9200:9200"
        - "9999:9999"
      networks:
        - webnet
  etd:
    build:
      context: ccetd/.
      dockerfile: Dockerfile   
  scholarship:
    build:
      context: cc-scholarship-graph/.
      dockerfile: Dockerfile  
  web:
    build:
      context: .
      dockerfile: DockerfileNginx
    deploy:
         replicas: 2
         resources:
           limits:
             cpus: "0.1"
             memory: 50M
         restart_policy:
           condition: on-failure
       ports: 
          - "80:80"
       networks:
          - webnet
networks:
  webnet:
      
