version: "3"
services:
  semanticserver:
    image: jermnelson/semantic-server-core:dev
    ports:
      - "8080:8080"
      - "9999:9999"

  etd:
    image: tuttlibrary/ccetd
    ports:
      - "8095:8095"

  scholarship:
    image: tuttlibrary/scholarship-graph 
    ports:
      - "7225:7225"

  web:
    image: tuttlibrary/production-web
    ports: 
      - "80:80"
      - "443:443"
