version: "2"
services:
  semanticserver:
    image: knowledgelinks/semantic-server
    ports:
      - "8080:8080"
      - "9999:9999"
      - "9200:9200"

  digital_cc:
    image: jermnelson/semantic-server-core:dev
    ports:
      - "8080:8080"
      - "9999:9999"

  etd:
    image: tuttlibrary/ccetd
    ports:
      - "8095:8095"

  scholarship:
    image: tuttlibrary/scholarship-graph 
    ports:
      - "7225:7225"

  marc_batch:
    image: tuttlibrary/marc-batch
    ports:
      - "20157:20157"

  fedora_utilities:
    image: tuttlibrary/fedora-utilities
    ports:
      - "9455:9455"

  web:
    image: tuttlibrary/production-web
    ports: 
      - "80:80"
      - "443:443"
