version: "2"
services:
  semantic_server:
    image: knowledgelinks/semantic-server
    ports:
      - "8080:8080"
      - "9999:9999"
      - "9200:9200"
    volumes:
      - /opt/dacc_search/elasticsearch:/opt/elasticsearch/data
    networks:
      - new

  digital_cc:
    image: tuttlibrary/digital-cc
    ports:
      - "5000:5000"
    networks:
      - new


  scholarship:
    image: tuttlibrary/scholarship-graph
    ports:
      - "7225:7225"
    networks:
      - new

  web:
    image: tuttlibrary/production-web
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - new

networks:
  new:
